language: java
dist: trusty
jdk: oraclejdk8
sudo: required
addons:
  sonarcloud:
    organization: "transbankdevelopers"
    token: $GITHUB_TOKEN
install: mvn --settings .travis/settings.xml clean compile
before_install:
  - if [ ! -z "$GPG_SECRET_KEYS" ]; then echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import; fi
  - if [ ! -z "$GPG_OWNERTRUST" ]; then echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust; fi
script:
  - mvn --settings .travis/settings.xml clean org.jacoco:jacoco-maven-plugin:prepare-agent package org.jacoco:jacoco-maven-plugin:report
  - wget https://github.com/TransbankDevelopers/bach/raw/releases/11/install-jdk.sh
  - chmod +x $TRAVIS_BUILD_DIR/install-jdk.sh
  - export JAVA_HOME=$HOME/openjdk11
  - $TRAVIS_BUILD_DIR/install-jdk.sh -F 11 --target $JAVA_HOME
  - mvn --settings .travis/settings.xml sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_LOGIN
after_success:
  - sonar-scanner
before_deploy:
  - java -version
  - jdk_switcher use oraclejdk8
  - java -version
deploy:
  -
    provider: script
    script: bash .travis/deploy.sh
    skip_cleanup: true
    on:
      all_branches: true
      jdk: oraclejdk8
