language: java
dist: trusty
jdk: oraclejdk8
sudo: required
addons:
  sonarcloud:
    organization: "transbankdevelopers"
    token:
      secure:"Nui1spHqyeYsW7YfB3uhtYK6NQU4EzpaDqlLIzM3xlx+TvAXg+dCGDhE0LRyLtH+Vvbqw7plntWAhDquQIPwKM/0P1WrXLw9l+Wd6olD1FlpXFXnr3+JboAVatoDI8se1qziEKKYlvk6i5TYYn1ajbbl461gcDDLJfjniOCQnAFh1WwbgH0fBJkiYo9LRKflksn5JtevvtTCsHmqozJfM2fIWSWwR/h3HmIxaTUYBdiBPntH3qWHgK5q1W9uR/ZHZTbjFrhGDk3CeDAuX/dAQMvsEDfMh4DOCDb+QP1X3n07qJkY0gRMkKtfUORBygssE/BgDvaqSQkwztjy2j3JBYrgEZDZW60tx7Mr004GX5c3egd6fkH06/CX858adtWjckrvXbjuMPZVSRxVVKceZ3OAW0wUYU5e86xbjOczz6cWMpB/+wYP3nlxmi0rdqY5E0BMcG5NY3r8jdDaHzoazz29lC9lSINcGld72lC4UJK9AI7in7FfCZPXrL7Ci3cBahLwkk+wZ3axyUh7F+AoJF1poTp0iCoJNuXDXf6LSMTIW2AZLaq2kw0qnVDDKIiCUtt2EHLVMQCYKEVqXcIHfE4nWGd3Q40J6htBkIJIN4TYtLYuAxGgoFBMXFXCca+RYkdOZ3nhsdW1qpz021KnLITJotC11fMdvHbdgRUVcfs="
install: mvn --settings .travis/settings.xml clean compile
before_install:
  - if [ ! -z "$GPG_SECRET_KEYS" ]; then echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import; fi
  - if [ ! -z "$GPG_OWNERTRUST" ]; then echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust; fi
script:
  - mvn --settings .travis/settings.xml clean org.jacoco:jacoco-maven-plugin:prepare-agent package org.jacoco:jacoco-maven-plugin:report
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
  - chmod +x $TRAVIS_BUILD_DIR/install-jdk.sh
  - export JAVA_HOME=$HOME/openjdk11
  - $TRAVIS_BUILD_DIR/install-jdk.sh -F 11 --target $JAVA_HOME
  - mvn --settings .travis/settings.xml sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_LOGIN
after_success:
  - sonar-scanner
before_deploy:
  - java -version
  - jdk_switcher use oraclejdk8
  - java -versiondeploy:
deploy:
  -
    provider: script
    script: bash .travis/deploy.sh
    skip_cleanup: true
    on:
      all_branches: true
      jdk: oraclejdk8
