/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cl.transbank.pos.utils;

public class BaseResponse {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BaseResponse(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BaseResponse obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        TransbankWrapJNI.delete_BaseResponse(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setFunction(int value) {
    TransbankWrapJNI.BaseResponse_function_set(swigCPtr, this, value);
  }

  public int getFunction() {
    return TransbankWrapJNI.BaseResponse_function_get(swigCPtr, this);
  }

  public void setResponseCode(int value) {
    TransbankWrapJNI.BaseResponse_responseCode_set(swigCPtr, this, value);
  }

  public int getResponseCode() {
    return TransbankWrapJNI.BaseResponse_responseCode_get(swigCPtr, this);
  }

  public void setCommerceCode(long value) {
    TransbankWrapJNI.BaseResponse_commerceCode_set(swigCPtr, this, value);
  }

  public long getCommerceCode() {
    return TransbankWrapJNI.BaseResponse_commerceCode_get(swigCPtr, this);
  }

  public void setTerminalId(String value) {
    TransbankWrapJNI.BaseResponse_terminalId_set(swigCPtr, this, value);
  }

  public String getTerminalId() {
    return TransbankWrapJNI.BaseResponse_terminalId_get(swigCPtr, this);
  }

  public void setInitilized(int value) {
    TransbankWrapJNI.BaseResponse_initilized_set(swigCPtr, this, value);
  }

  public int getInitilized() {
    return TransbankWrapJNI.BaseResponse_initilized_get(swigCPtr, this);
  }

  public BaseResponse() {
    this(TransbankWrapJNI.new_BaseResponse(), true);
  }

}
