package cl.transbank.pos.utils;

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class ParamInfo {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ParamInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ParamInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        TransbankWrapJNI.delete_ParamInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setIndex(int value) {
    TransbankWrapJNI.ParamInfo_index_set(swigCPtr, this, value);
  }

  public int getIndex() {
    return TransbankWrapJNI.ParamInfo_index_get(swigCPtr, this);
  }

  public void setLength(int value) {
    TransbankWrapJNI.ParamInfo_length_set(swigCPtr, this, value);
  }

  public int getLength() {
    return TransbankWrapJNI.ParamInfo_length_get(swigCPtr, this);
  }

  public ParamInfo() {
    this(TransbankWrapJNI.new_ParamInfo(), true);
  }

}
