/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cl.transbank.pos.utils;

public class RefundCResponse {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected RefundCResponse(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RefundCResponse obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        TransbankWrapJNI.delete_RefundCResponse(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setFunction(int value) {
    TransbankWrapJNI.RefundCResponse_function_set(swigCPtr, this, value);
  }

  public int getFunction() {
    return TransbankWrapJNI.RefundCResponse_function_get(swigCPtr, this);
  }

  public void setResponseCode(int value) {
    TransbankWrapJNI.RefundCResponse_responseCode_set(swigCPtr, this, value);
  }

  public int getResponseCode() {
    return TransbankWrapJNI.RefundCResponse_responseCode_get(swigCPtr, this);
  }

  public void setCommerceCode(long value) {
    TransbankWrapJNI.RefundCResponse_commerceCode_set(swigCPtr, this, value);
  }

  public long getCommerceCode() {
    return TransbankWrapJNI.RefundCResponse_commerceCode_get(swigCPtr, this);
  }

  public void setTerminalId(String value) {
    TransbankWrapJNI.RefundCResponse_terminalId_set(swigCPtr, this, value);
  }

  public String getTerminalId() {
    return TransbankWrapJNI.RefundCResponse_terminalId_get(swigCPtr, this);
  }

  public void setAuthorizationCode(String value) {
    TransbankWrapJNI.RefundCResponse_authorizationCode_set(swigCPtr, this, value);
  }

  public String getAuthorizationCode() {
    return TransbankWrapJNI.RefundCResponse_authorizationCode_get(swigCPtr, this);
  }

  public void setOperationID(int value) {
    TransbankWrapJNI.RefundCResponse_operationID_set(swigCPtr, this, value);
  }

  public int getOperationID() {
    return TransbankWrapJNI.RefundCResponse_operationID_get(swigCPtr, this);
  }

  public void setInitilized(int value) {
    TransbankWrapJNI.RefundCResponse_initilized_set(swigCPtr, this, value);
  }

  public int getInitilized() {
    return TransbankWrapJNI.RefundCResponse_initilized_get(swigCPtr, this);
  }

  public RefundCResponse() {
    this(TransbankWrapJNI.new_RefundCResponse(), true);
  }

}
