/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cl.transbank.pos.utils;

public enum TbkBaudRate {
  TBK_1200(1200),
  TBK_2400(2400),
  TBK_4800(4800),
  TBK_9600(9600),
  TBK_19200(19200),
  TBK_115200(115200);

  public final int swigValue() {
    return swigValue;
  }

  public static TbkBaudRate swigToEnum(int swigValue) {
    TbkBaudRate[] swigValues = TbkBaudRate.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (TbkBaudRate swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + TbkBaudRate.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private TbkBaudRate() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private TbkBaudRate(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private TbkBaudRate(TbkBaudRate swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

