/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cl.transbank.pos.utils;

public final class TbkReturn {
  public final static TbkReturn TBK_OK = new TbkReturn("TBK_OK", TransbankWrapJNI.TBK_OK_get());
  public final static TbkReturn TBK_NOK = new TbkReturn("TBK_NOK", TransbankWrapJNI.TBK_NOK_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static TbkReturn swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + TbkReturn.class + " with value " + swigValue);
  }

  private TbkReturn(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private TbkReturn(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private TbkReturn(String swigName, TbkReturn swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static TbkReturn[] swigValues = { TBK_OK, TBK_NOK };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

