package cl.transbank.pos.utils;

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class TotalsCResponse {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected TotalsCResponse(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TotalsCResponse obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        TransbankWrapJNI.delete_TotalsCResponse(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setFunction(int value) {
    TransbankWrapJNI.TotalsCResponse_function_set(swigCPtr, this, value);
  }

  public int getFunction() {
    return TransbankWrapJNI.TotalsCResponse_function_get(swigCPtr, this);
  }

  public void setResponseCode(int value) {
    TransbankWrapJNI.TotalsCResponse_responseCode_set(swigCPtr, this, value);
  }

  public int getResponseCode() {
    return TransbankWrapJNI.TotalsCResponse_responseCode_get(swigCPtr, this);
  }

  public void setTxCount(int value) {
    TransbankWrapJNI.TotalsCResponse_txCount_set(swigCPtr, this, value);
  }

  public int getTxCount() {
    return TransbankWrapJNI.TotalsCResponse_txCount_get(swigCPtr, this);
  }

  public void setTxTotal(int value) {
    TransbankWrapJNI.TotalsCResponse_txTotal_set(swigCPtr, this, value);
  }

  public int getTxTotal() {
    return TransbankWrapJNI.TotalsCResponse_txTotal_get(swigCPtr, this);
  }

  public void setInitilized(int value) {
    TransbankWrapJNI.TotalsCResponse_initilized_set(swigCPtr, this, value);
  }

  public int getInitilized() {
    return TransbankWrapJNI.TotalsCResponse_initilized_get(swigCPtr, this);
  }

  public TotalsCResponse() {
    this(TransbankWrapJNI.new_TotalsCResponse(), true);
  }

}
