/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cl.transbank.pos.utils;

public class TransbankWrapJNI {
  public final static native void ParamInfo_index_set(long jarg1, ParamInfo jarg1_, int jarg2);
  public final static native int ParamInfo_index_get(long jarg1, ParamInfo jarg1_);
  public final static native void ParamInfo_length_set(long jarg1, ParamInfo jarg1_, int jarg2);
  public final static native int ParamInfo_length_get(long jarg1, ParamInfo jarg1_);
  public final static native long new_ParamInfo();
  public final static native void delete_ParamInfo(long jarg1);
  public final static native void BaseResponse_function_set(long jarg1, BaseResponse jarg1_, int jarg2);
  public final static native int BaseResponse_function_get(long jarg1, BaseResponse jarg1_);
  public final static native void BaseResponse_responseCode_set(long jarg1, BaseResponse jarg1_, int jarg2);
  public final static native int BaseResponse_responseCode_get(long jarg1, BaseResponse jarg1_);
  public final static native void BaseResponse_commerceCode_set(long jarg1, BaseResponse jarg1_, long jarg2);
  public final static native long BaseResponse_commerceCode_get(long jarg1, BaseResponse jarg1_);
  public final static native void BaseResponse_terminalId_set(long jarg1, BaseResponse jarg1_, String jarg2);
  public final static native String BaseResponse_terminalId_get(long jarg1, BaseResponse jarg1_);
  public final static native void BaseResponse_initilized_set(long jarg1, BaseResponse jarg1_, int jarg2);
  public final static native int BaseResponse_initilized_get(long jarg1, BaseResponse jarg1_);
  public final static native long new_BaseResponse();
  public final static native void delete_BaseResponse(long jarg1);
  public final static native void TotalsCResponse_function_set(long jarg1, TotalsCResponse jarg1_, int jarg2);
  public final static native int TotalsCResponse_function_get(long jarg1, TotalsCResponse jarg1_);
  public final static native void TotalsCResponse_responseCode_set(long jarg1, TotalsCResponse jarg1_, int jarg2);
  public final static native int TotalsCResponse_responseCode_get(long jarg1, TotalsCResponse jarg1_);
  public final static native void TotalsCResponse_txCount_set(long jarg1, TotalsCResponse jarg1_, int jarg2);
  public final static native int TotalsCResponse_txCount_get(long jarg1, TotalsCResponse jarg1_);
  public final static native void TotalsCResponse_txTotal_set(long jarg1, TotalsCResponse jarg1_, int jarg2);
  public final static native int TotalsCResponse_txTotal_get(long jarg1, TotalsCResponse jarg1_);
  public final static native void TotalsCResponse_initilized_set(long jarg1, TotalsCResponse jarg1_, int jarg2);
  public final static native int TotalsCResponse_initilized_get(long jarg1, TotalsCResponse jarg1_);
  public final static native long new_TotalsCResponse();
  public final static native void delete_TotalsCResponse(long jarg1);
  public final static native void RefundCResponse_function_set(long jarg1, RefundCResponse jarg1_, int jarg2);
  public final static native int RefundCResponse_function_get(long jarg1, RefundCResponse jarg1_);
  public final static native void RefundCResponse_responseCode_set(long jarg1, RefundCResponse jarg1_, int jarg2);
  public final static native int RefundCResponse_responseCode_get(long jarg1, RefundCResponse jarg1_);
  public final static native void RefundCResponse_commerceCode_set(long jarg1, RefundCResponse jarg1_, long jarg2);
  public final static native long RefundCResponse_commerceCode_get(long jarg1, RefundCResponse jarg1_);
  public final static native void RefundCResponse_terminalId_set(long jarg1, RefundCResponse jarg1_, String jarg2);
  public final static native String RefundCResponse_terminalId_get(long jarg1, RefundCResponse jarg1_);
  public final static native void RefundCResponse_authorizationCode_set(long jarg1, RefundCResponse jarg1_, String jarg2);
  public final static native String RefundCResponse_authorizationCode_get(long jarg1, RefundCResponse jarg1_);
  public final static native void RefundCResponse_operationID_set(long jarg1, RefundCResponse jarg1_, int jarg2);
  public final static native int RefundCResponse_operationID_get(long jarg1, RefundCResponse jarg1_);
  public final static native void RefundCResponse_initilized_set(long jarg1, RefundCResponse jarg1_, int jarg2);
  public final static native int RefundCResponse_initilized_get(long jarg1, RefundCResponse jarg1_);
  public final static native long new_RefundCResponse();
  public final static native void delete_RefundCResponse(long jarg1);
  public final static native String list_ports();
  public final static native String get_port_name(long jarg1);
  public final static native int read_bytes(long jarg1, String jarg2, long jarg3);
  public final static native int read_ack(long jarg1);
  public final static native short calculate_lrc(String jarg1, int jarg2);
  public final static native int reply_ack(long jarg1, String jarg2, int jarg3);
  public final static native int write_message(long jarg1, long jarg2);
  public final static native int open_port(String jarg1, int jarg2);
  public final static native String sale(int jarg1, String jarg2, boolean jarg3);
  public final static native String last_sale();
  public final static native long do_close();
  public final static native long load_keys();
  public final static native long get_totals();
  public final static native int do_poll();
  public final static native int set_normal_mode();
  public final static native int close_port();
  public final static native long refund(int jarg1);
  public final static native String sales_detail(boolean jarg1);
}
