/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cl.transbank.pos.utils;

public class TransbankWrap {
  public static String list_ports() {
    return TransbankWrapJNI.list_ports();
  }

  public static String get_port_name(SWIGTYPE_p_sp_port port) {
    return TransbankWrapJNI.get_port_name(SWIGTYPE_p_sp_port.getCPtr(port));
  }

  public static int read_bytes(SWIGTYPE_p_sp_port port, String buf, SWIGTYPE_p_Message message) {
    return TransbankWrapJNI.read_bytes(SWIGTYPE_p_sp_port.getCPtr(port), buf, SWIGTYPE_p_Message.getCPtr(message));
  }

  public static int read_ack(SWIGTYPE_p_sp_port port) {
    return TransbankWrapJNI.read_ack(SWIGTYPE_p_sp_port.getCPtr(port));
  }

  public static short calculate_lrc(String message, int length) {
    return TransbankWrapJNI.calculate_lrc(message, length);
  }

  public static int reply_ack(SWIGTYPE_p_sp_port port, String message, int length) {
    return TransbankWrapJNI.reply_ack(SWIGTYPE_p_sp_port.getCPtr(port), message, length);
  }

  public static int write_message(SWIGTYPE_p_sp_port port, SWIGTYPE_p_Message message) {
    return TransbankWrapJNI.write_message(SWIGTYPE_p_sp_port.getCPtr(port), SWIGTYPE_p_Message.getCPtr(message));
  }

  public static TbkReturn open_port(String portName, int baudrate) {
    return TbkReturn.swigToEnum(TransbankWrapJNI.open_port(portName, baudrate));
  }

  public static String sale(int amount, String ticket, boolean send_messages) {
    return TransbankWrapJNI.sale(amount, ticket, send_messages);
  }

  public static String last_sale() {
    return TransbankWrapJNI.last_sale();
  }

  public static BaseResponse do_close() {
    return new BaseResponse(TransbankWrapJNI.do_close(), true);
  }

  public static BaseResponse load_keys() {
    return new BaseResponse(TransbankWrapJNI.load_keys(), true);
  }

  public static TotalsCResponse get_totals() {
    return new TotalsCResponse(TransbankWrapJNI.get_totals(), true);
  }

  public static TbkReturn do_poll() {
    return TbkReturn.swigToEnum(TransbankWrapJNI.do_poll());
  }

  public static TbkReturn set_normal_mode() {
    return TbkReturn.swigToEnum(TransbankWrapJNI.set_normal_mode());
  }

  public static TbkReturn close_port() {
    return TbkReturn.swigToEnum(TransbankWrapJNI.close_port());
  }

  public static RefundCResponse refund(int transactionID) {
    return new RefundCResponse(TransbankWrapJNI.refund(transactionID), true);
  }

  public static String sales_detail(boolean print_on_pos) {
    return TransbankWrapJNI.sales_detail(print_on_pos);
  }

}
